## Baseline Model

In [17]:
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, median_absolute_error, r2_score

### Sélection de variables

In [18]:
train_data = pd.read_csv("../data/processed_dataset.csv")
test_data = pd.read_parquet("../data/test_data.parquet")

test_data.head()

,IdentifiantMaison,Chambres,Salon,SalleDeBainInterieure,Parking,Meuble,Jardin,Superficie_m2,DistanceRoute_m,Quartier,AgeMaison,LoyerMensuel_BIF,Salon_Bin,SalleDeBainInterieure_Bin,Parking_Bin,Meuble_Bin,Jardin_Bin,Quartier_Target,LoyerMensuel_Log1
0,433,1.0,Oui,Oui,Oui,Non,Non,-1.324731,1.767565,Buyenzi,-1.377334,268868,1,1,1,0,0,0.010428,12.501980
1,398,2.0,Oui,Oui,Oui,Non,Non,-0.493541,-1.035941,Kiriri,1.457576,1536788,1,1,1,0,0,0.001998,14.245206
2,432,5.0,Oui,Oui,Non,Non,Oui,1.262683,-1.458883,Buyenzi,0.217303,889633,1,1,0,0,1,0.010428,13.698565
3,371,4.0,Oui,Oui,Non,Non,Non,1.128620,-0.129635,Gihosha,-1.465925,1657285,1,1,0,0,0,0.002163,14.320692
4,407,1.0,Non,Oui,Oui,Non,Non,-1.700107,-0.093383,Ngagara,0.660257,507985,0,1,1,0,0,0.002146,13.138209

In [19]:
X_train = train_data.drop(
    ["LoyerMensuel_Log1", "LoyerMensuel_BIF", "IdentifiantMaison"],
    axis=1).select_dtypes(include=["number"])
y_train = train_data["LoyerMensuel_Log1"]

### Transformation de données de test

In [20]:
# Les variables numériques
# feature_cols = ["AgeMaison", "Quartier_Target", "Indicateur_Confort", "Chambres_par_Superficie", "LoyerMensuel_Log1"]

# for col in ['Salon', 'SalleDeBainInterieure', 'Parking', 'Meuble', 'Jardin']:
#     test_data[col + "_Bin"] = test_data[col].map({"Oui": 1, "Non": 0}).fillna(0).astype(int)

# neighbourhood_encoder = joblib.load("neighbourhood_encoder.joblib") 
# test_data["Quartier_Target"] = neighbourhood_encoder.transform(test_data[["Quartier"]])[:, 0]

# test_data["LoyerMensuel_Log1"] = np.log1p(test_data["LoyerMensuel_BIF"])

# Création de variables utiles pour le test
# cols_confort = ['Salon_Bin', 'SalleDeBainInterieure_Bin', 'Parking_Bin', 'Meuble_Bin', 'Jardin_Bin']
# test_data['Indicateur_Confort'] = test_data[cols_confort].sum(axis=1)

# test_data['Chambres_par_Superficie'] = test_data['Chambres'] / (test_data['Superficie_m2'] + 0.1)

# Séparation de X_test et y_test
X_test = test_data.drop(
    ["LoyerMensuel_Log1", "LoyerMensuel_BIF", "IdentifiantMaison"],
    axis=1).select_dtypes(include=["number"])
y_test = test_data["LoyerMensuel_Log1"]

X_test

,Chambres,Superficie_m2,DistanceRoute_m,AgeMaison,Salon_Bin,SalleDeBainInterieure_Bin,Parking_Bin,Meuble_Bin,Jardin_Bin,Quartier_Target
0,1.0,-1.324731,1.767565,-1.377334,1,1,1,0,0,0.010428
1,2.0,-0.493541,-1.035941,1.457576,1,1,1,0,0,0.001998
2,5.0,1.262683,-1.458883,0.217303,1,1,0,0,1,0.010428
3,4.0,1.128620,-0.129635,-1.465925,1,1,0,0,0,0.002163
4,1.0,-1.700107,-0.093383,0.660257,0,1,1,0,0,0.002146
...,...,...,...,...,...,...,...,...,...,...
123,4.0,0.578962,0.389980,0.571666,1,1,1,0,1,0.002029
124,5.0,0.538743,-0.322980,-0.668606,1,1,1,0,1,0.001998
125,6.0,1.195651,-0.480073,0.837439,1,1,1,0,1,0.002014
126,4.0,0.176773,0.716250,-0.402834,1,1,0,1,1,0.002163
127,4.0,-0.051133,0.160383,0.483076,1,1,0,0,0,0.002182

### Dummy Régression

In [21]:
model_dummy_mean = DummyRegressor(strategy="mean").fit(X_train, y_train)
model_dummy_median = DummyRegressor(strategy="median").fit(X_train, y_train)

y_predict_dummy_mean = model_dummy_mean.predict(y_test)
y_predict_dummy_median = model_dummy_median.predict(y_test)

print(f"y_predict_dummy_mean : {y_predict_dummy_mean}")
print()
print(f"y_predict_dummy_median : {y_predict_dummy_median}")

y_predict_dummy_mean : [13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581 13.84418581
 13.84418581 13.84418581]

y_predict_dummy_median : [13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279 13.88505279
 13.88505279 13.88505279]

### Régression Linéaire simple

In [22]:
model = LinearRegression().fit(X_train, y_train)
y_predict = model.predict(X_test)

y_predict_series = pd.Series(y_predict, index=y_test.index)

compareson = pd.DataFrame({
    "Réel": y_test,
    "Prédict": y_predict_series
})

print(compareson.head(3))

        Réel    Prédict
0  12.501980  12.578561
1  14.245206  13.505785
2  13.698565  13.707224

### Analyse des erreurs

In [23]:
print(f"LinearModel : {round(mean_squared_error(y_test, y_predict), 2)}")
print(f"dummy median : {round(median_absolute_error(y_test, y_predict_dummy_median), 2)}")
print(f"dummy mean : {round(mean_squared_error(y_test, y_predict_dummy_mean), 2)}")

print()

print(f"r2_Score dummpy mean : {r2_score(y_test, y_predict_dummy_mean)}")
print(f"r2_Score dummpy median : {r2_score(y_test, y_predict_dummy_median)}")
print(f"r2_Score LinearModel : {r2_score(y_test, y_predict)}")

LinearModel : 0.17
dummy median : 0.53
dummy mean : 0.49

r2_Score dummpy mean : -0.0025295733210484173
r2_Score dummpy median : -6.738911133985503e-05
r2_Score LinearModel : 0.6465849476951521